flowchart TD
    subprogram1 --> subprogram2
    Q{condition} -->|Yes| subprogram3
    Q -->|No| subprogram4
    R{condition} -->|Yes| subprogram5
    R{condition} -->|No| subprogram6
    subprogram5 --> R
